# Generated by Django 4.2.17 on 2025-01-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0002_otp"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_name", models.CharField(max_length=100)),
                ("staff_id", models.CharField(max_length=20, unique=True)),
                (
                    "staff_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("staff_details", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
