# Generated by Django 4.2.17 on 2025-01-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0003_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="staff_subject",
            field=models.CharField(
                choices=[
                    ("tamil", "Tamil"),
                    ("english", "English"),
                    ("maths", "Mathematics"),
                    ("physics", "Physics"),
                    ("chemistry", "Chemistry"),
                    ("biology", "Biology"),
                    ("history", "History"),
                    ("geography", "Geography"),
                    ("computer_science", "Computer Science"),
                    ("commerce", "Commerce"),
                    ("economics", "Economics"),
                    ("accounting", "Accounting"),
                    ("business_studies", "Business Studies"),
                    ("political_science", "Political Science"),
                    ("psychology", "Psychology"),
                    ("sociology", "Sociology"),
                    ("philosophy", "Philosophy"),
                    ("statistics", "Statistics"),
                    ("botany", "Botany"),
                    ("zoology", "Zoology"),
                    ("microbiology", "Microbiology"),
                    ("biotechnology", "Biotechnology"),
                    ("electronics", "Electronics"),
                    ("mechanical", "Mechanical Engineering"),
                    ("civil", "Civil Engineering"),
                    ("electrical", "Electrical Engineering"),
                    ("information_technology", "Information Technology"),
                    ("management", "Management"),
                    ("law", "Law"),
                    ("environmental_science", "Environmental Science"),
                ],
                default="law",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
