# Generated by Django 4.2.17 on 2025-01-13 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0004_staff_staff_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="Arrear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("tamil", "Tamil"),
                            ("english", "English"),
                            ("maths", "Mathematics"),
                            ("physics", "Physics"),
                            ("chemistry", "Chemistry"),
                            ("biology", "Biology"),
                            ("history", "History"),
                            ("geography", "Geography"),
                            ("computer_science", "Computer Science"),
                            ("commerce", "Commerce"),
                            ("economics", "Economics"),
                            ("accounting", "Accounting"),
                            ("business_studies", "Business Studies"),
                            ("political_science", "Political Science"),
                            ("psychology", "Psychology"),
                            ("sociology", "Sociology"),
                            ("philosophy", "Philosophy"),
                            ("statistics", "Statistics"),
                            ("botany", "Botany"),
                            ("zoology", "Zoology"),
                            ("microbiology", "Microbiology"),
                            ("biotechnology", "Biotechnology"),
                            ("electronics", "Electronics"),
                            ("mechanical", "Mechanical Engineering"),
                            ("civil", "Civil Engineering"),
                            ("electrical", "Electrical Engineering"),
                            ("information_technology", "Information Technology"),
                            ("management", "Management"),
                            ("law", "Law"),
                            ("environmental_science", "Environmental Science"),
                        ],
                        max_length=90,
                    ),
                ),
                (
                    "semester",
                    models.IntegerField(
                        choices=[
                            (1, "Semester 1"),
                            (2, "Semester 2"),
                            (3, "Semester 3"),
                            (4, "Semester 4"),
                            (5, "Semester 5"),
                            (6, "Semester 6"),
                            (7, "Semester 7"),
                            (8, "Semester 8"),
                        ]
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.student"
                    ),
                ),
            ],
        ),
    ]
