# Generated by Django 4.2.17 on 2025-02-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0005_arrear"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="student_pan",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
