# Generated by Django 4.2.17 on 2025-03-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0006_student_student_pan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_course",
            field=models.CharField(
                choices=[
                    ("CS", "Computer Science"),
                    ("IT", "Information Technology"),
                    ("ECE", "Electronics"),
                    ("ME", "Mechanical"),
                    ("CE", "Civil"),
                ],
                default="Computer Science",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_year",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "First Year"),
                    (2, "Second Year"),
                    (3, "Third Year"),
                    (4, "Final Year"),
                ],
                default="First Year",
            ),
        ),
    ]
