# Generated by Django 4.2.17 on 2025-03-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0008_alter_student_student_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="student_profile",
            field=models.ImageField(
                blank=True, null=True, upload_to="students_profile"
            ),
        ),
    ]
