# Generated by Django 4.2.17 on 2025-03-19 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0009_student_student_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="student_class_staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app1.staff",
            ),
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semester",
                    models.IntegerField(
                        choices=[
                            (1, "Semester 1"),
                            (2, "Semester 2"),
                            (3, "Semester 3"),
                            (4, "Semester 4"),
                            (5, "Semester 5"),
                            (6, "Semester 6"),
                            (7, "Semester 7"),
                            (8, "Semester 8"),
                        ]
                    ),
                ),
                ("percentage", models.FloatField()),
                (
                    "std",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.student"
                    ),
                ),
            ],
        ),
    ]
